### PR TITLE
introduce formatter

### PR DESCRIPTION
**Pull request by togishima**
I greatly appreciate this project as this has saved me a lot of time in adding another channel for teams with monolog.
However, I wanted to make the looks of the message just a bit neater and hence created a small class to support it.

This extra class will change this 
image
into this
image

it'll be a small change and may not be a big change, but hope this helps in some way :)

### CODE REVIEW

**Comment by garrettw** [comment]
Yes please! Can we get this merged in??

**Comment by togishima** [comment]
Anytime :)

**Comment by garrettw** [comment]
I have just tested this branch as I was intending to use it, and it does not work. The only messages that showed up in Teams were of the "info" level -- no errors or warnings.

**Comment by togishima** [comment]
@garrettw 
wired...do you have your handler level set right? when testing?
the formatter should have nothing to do with log level, so I'm doubting that it's something else...

**Comment by garrettw** [comment]
Yes, that's not it. Errors were sent to other handlers just fine.

I ended up using a different library: https://github.com/actived/microsoft-teams-notifier
and it worked out much better.

**Pull request merged**
